global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']
    scrape_interval: 5s

  - job_name: 'detector-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['detector-service:8081']
    scrape_interval: 5s

  - job_name: 'auditor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auditor-service:8082']
    scrape_interval: 5s